# Generated by Django 3.0.4 on 2020-09-03 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20200903_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(default=datetime.date(2020, 9, 3)),
        ),
    ]
