# Generated by Django 3.0.4 on 2020-09-03 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20200903_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
